#!/bin/sh
#
# elasticsearch -- startup script for elasticsearch4
#
# chkconfig: - 85 15
# processname: elasticsearch
# pidfile: /var/run/elasticsearch.pid
# description: Kibana is a webui to visualize data
#
### BEGIN INIT INFO
# Provides: elasticsearch
# Required-Start: $local_fs $remote_fs $network
# Required-Stop: $local_fs $remote_fs $network
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: start and stop elasticsearch
### END INIT INFO
#
#
. /lib/lsb/init-functions

PIDFILE="/var/run/elasticsearch.pid"
ELASTICSEARCH_DIR="/opt/elasticsearch/"

start() {
        echo -n "Starting Kibana Daemon: "
        if [ -f $PIDFILE ]; then
                PID=`cat $PIDFILE`
                echo Kibana already running: $PID
                exit 1;
        else
                cd $ELASTICSEARCH_DIR
                PID=`./bin/elasticsearch >/dev/null 2>&1 & echo $! > $PIDFILE`
                echo `cat $PIDFILE`
        fi

}

stop() {
        echo -n "Shutting down Kibana Daemon: "
        echo
        killproc elasticsearch
        echo
        rm -f /var/lock/subsys/elasticsearch
        return 0
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        status elasticsearch
        ;;
    restart)
        stop
        start
        ;;
    *)
        echo "Usage:  {start|stop|status|restart}"
        exit 1
        ;;
esac
exit $?
